version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - default

networks:
  real-time:
    driver: bridge
